#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 80?
sudo service nginx stop
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
