#!/usr/bin/env bash
# gives you information about the holbertonschool file
a="holbertonschool"
if [ -e $a ]
then
    echo holbertonschool file exists
else
    echo holbertonschool file does not exist
    exit 0
fi
if [ -s $a ]
then
    echo holbertonschool file is not empty
else
    echo holbertonschool file is empty
fi
if [ -f $a ]
then
    echo holbertonschool is a regular file
fi